// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb5JTozEmJSiujXHjc1F_DHjWT_2Gu_W0',
    appId: '1:717190502764:web:fb2428b96a3313e2eefb49',
    messagingSenderId: '717190502764',
    projectId: 'authtestapp-d4730',
    authDomain: 'authtestapp-d4730.firebaseapp.com',
    storageBucket: 'authtestapp-d4730.firebasestorage.app',
    measurementId: 'G-3HD163Y4L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEgkjIVlcWZKQT_7v0rs9QUcvZzvYFu5U',
    appId: '1:717190502764:android:687176cb0d4aebaaeefb49',
    messagingSenderId: '717190502764',
    projectId: 'authtestapp-d4730',
    storageBucket: 'authtestapp-d4730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrYGctFs9mr2fIp0O8dQ_wyHBRymtey_I',
    appId: '1:717190502764:ios:eef8dc9619066437eefb49',
    messagingSenderId: '717190502764',
    projectId: 'authtestapp-d4730',
    storageBucket: 'authtestapp-d4730.firebasestorage.app',
    iosClientId: '717190502764-l85crd0fct15ubk7peandr6atjleqv9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFlowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrYGctFs9mr2fIp0O8dQ_wyHBRymtey_I',
    appId: '1:717190502764:ios:eef8dc9619066437eefb49',
    messagingSenderId: '717190502764',
    projectId: 'authtestapp-d4730',
    storageBucket: 'authtestapp-d4730.firebasestorage.app',
    iosClientId: '717190502764-l85crd0fct15ubk7peandr6atjleqv9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFlowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb5JTozEmJSiujXHjc1F_DHjWT_2Gu_W0',
    appId: '1:717190502764:web:81a15b5f5da2047beefb49',
    messagingSenderId: '717190502764',
    projectId: 'authtestapp-d4730',
    authDomain: 'authtestapp-d4730.firebaseapp.com',
    storageBucket: 'authtestapp-d4730.firebasestorage.app',
    measurementId: 'G-HXZWFYLSG3',
  );
}
